---
- hosts: localhost
  vars:
    state: present
    bucket: javahome-tf-1212
    region: us-east-1
    key: terraform.tfstate
    project_env: dev
  tasks:
    - name: Run terraform scripts
      terraform:
        project_path: "./"
        state: "{{ state }}"
        backend_config:
          region: "{{ region }}"
          bucket: "{{ bucket }}"
          key: "{{ key }}"
        variables_file: "{{ project_env }}.tfvars"
